apiVersion: v1
kind: Service
metadata:
  name: {{ include "ryuchart.fullname" . }}
  labels:
    {{- include "ryuchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6633
      targetPort: 6633
      protocol: TCP
      name: openflow
  selector:
    {{- include "ryuchart.selectorLabels" . | nindent 4 }}
